name: test_actions
on: [push]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Run cmake --version
        shell: bash
        run: |
          VERSION=`cmake --version`
          echo $VERSION

      - name: build
        shell: bash
        run: |
          cd formatter_lib
          cmake -H\. -B_build -DCMAKE_INSTALL_PREFIX=_install
          cmake --build _build --target install
          
          cd ../formatter_ex_lib
          cmake -H\. -B_build -DCMAKE_INSTALL_PREFIX=_install
          cmake --build _build --target install
         
          cd ../solver_lib
          cmake -H\. -B_build -DCMAKE_INSTALL_PREFIX=_install
          cmake --build _build --target install

          cd ..
          cmake -H\. -B_build
          cmake --build _build

      - name: Run examples
        shell: bash
        run: |
          ls -la
          cd _build
	  ls -la
          ./hello_world_ex.out
          echo "1 10 20" | ./solver_ex.out